### ISSUE TITLE
sorting is not working in every case

### ISSUE THREAD

**Issue by HKskn** [adamhooper/js-priority-queue#13]
Please test the code below

```
const list = new priorityQueue(function(a,b){ return a.value - b.value; });
list.enq({id: 2, value: 2});
list.enq({id: 1, value: 1});
list.enq({id: 3, value: 3});

list.forEach(element => {
  console.log(element)
})
```
output:

```
{ id: 3, value: 3 }
{ id: 1, value: 1 }
{ id: 2, value: 2 }
```

**Comment by adamhooper** [comment]
Hi there,

I think you may be logging an issue with the wrong JavaScript priority-queue library. Did you mean https://github.com/janogonzalez/priorityqueuejs?

_This_ library uses a `comparator` argument, and it has no `forEach` method.
