### ISSUE TITLE
Not an issue, but a suggestion: add "dequeueLast"!

### ISSUE THREAD

**Issue by ruslanx3m** [adamhooper/js-priority-queue#15]
something like this

```
                BinaryHeapStrategy.prototype.dequeueLast = function () {
                    if (this.data.length === 0) {
                        return null; // or throw an exception, depending on your use case
                    }
                    var ret = this.data[this.data.length - 1];
                    this.data.pop();
                    if (this.data.length > 0) {
                        this._heapify();
                    }
                    return ret;
                };
```

Not an issue, but a suggestion: add "dequeueLast"!

**Comment by adamhooper** [comment]
This isn't how heaps work :). You'd need to scan the entire bottom row of data to find the last entry, which is O(n). At that point, you might as well use a sorted Array -- this library wouldn't be giving any value over a sorted Array.

You are, of course, welcome to fork and experiment.

**Comment by ruslanx3m** [comment]
Now I am using to get last in queue
```
this.tokenQueue.priv.data.reverse();
token = this.tokenQueue.dequeue().token;
this.tokenQueue.priv.data.reverse();
```

I need 2 mods LIFO and FIFO

**Comment by adamhooper** [comment]
I suggest you use a different library, or build your own. You can fork ArrayStrategy to start, if you want.

You're asking for a double-ended priority queue, and that isn't what this library does. The heap and bheap in this library simply don't do what you want.
